import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/About.module.css'
import data from '../data/eeomployees.json'
import { useState } from 'react'
import Card from '../components/Card'
import Link from 'next/link'

export default function About() {
    return(
        <> About Page</>
    )
}
export default function About() {
    const [information, setInformation] = useState([...data])
     console.log(data);
  return (
 <>
<Head>
    <title>The Office</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
</Head>
<main className={styles.main}>
   
          
<div className={styles.grid}>
<b> Employee One </b>
{information && information.map((info, About) => {
if (info.employeePosition === "manager") {
return (
<Card key={About} degree={info.employeeName} colour="hotPink" font="15px" />
 )
 }
})}
<b> Employee Two:</b>
{information && information.map((info, About) => {
if (info.department === "Computing") {
     return (
    <Card key={index} degree={info.degree} colour="lightPink" font="15px" />
     )
     }
     })}
    </div>
    </main>
   
</>
  )
    }  
        









